name: NoItemFrameDN
author: Strahan
main: com.sylvcraft.NoItemFrameDN
version: 1.21
description: Removes display name from item when placed in an ItemFrame
commands:
  nodn:
    description: Plugin command
